"""init tables

Revision ID: 35a8cfc36763
Revises: 
Create Date: 2026-09-03 10:42:49.971627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a8cfc36763'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('last_message_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_message_id'], ['messages.message_id'], name='fk_conversations_last_message_id_messages', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('customer',
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('customer_unique_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('customer_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('customer_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('customer_state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_customer_unique_id'), 'customer', ['customer_unique_id'], unique=False)
    op.create_index(op.f('ix_customer_customer_zip_code_prefix'), 'customer', ['customer_zip_code_prefix'], unique=False)
    op.create_table('geolocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geolocation_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('geolocation_lat', sa.Float(), nullable=False),
    sa.Column('geolocation_lng', sa.Float(), nullable=False),
    sa.Column('geolocation_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('geolocation_state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geolocation_geolocation_zip_code_prefix'), 'geolocation', ['geolocation_zip_code_prefix'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('product_category_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('product_name_lenght', sa.Integer(), nullable=True),
    sa.Column('product_description_lenght', sa.Integer(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Integer(), nullable=True),
    sa.Column('product_length_cm', sa.Integer(), nullable=True),
    sa.Column('product_height_cm', sa.Integer(), nullable=True),
    sa.Column('product_width_cm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_product_category_name'), 'product', ['product_category_name'], unique=False)
    op.create_table('productcategorynametranslation',
    sa.Column('product_category_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('product_category_name_english', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('product_category_name')
    )
    op.create_table('seller',
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('seller_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('seller_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('seller_state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_index(op.f('ix_seller_seller_zip_code_prefix'), 'seller', ['seller_zip_code_prefix'], unique=False)
    op.create_table('todo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.message_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('order',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_order_status'), 'order', ['order_status'], unique=False)
    op.create_table('orderitem',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('shipping_limit_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_index(op.f('ix_orderitem_product_id'), 'orderitem', ['product_id'], unique=False)
    op.create_index(op.f('ix_orderitem_seller_id'), 'orderitem', ['seller_id'], unique=False)
    op.create_table('orderpayment',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.create_table('orderreview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('review_comment_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('review_comment_message', sa.Text(), nullable=True),
    sa.Column('review_creation_date', sa.DateTime(), nullable=False),
    sa.Column('review_answer_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderreview_order_id'), 'orderreview', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderreview_review_id'), 'orderreview', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderreview_review_id'), table_name='orderreview')
    op.drop_index(op.f('ix_orderreview_order_id'), table_name='orderreview')
    op.drop_table('orderreview')
    op.drop_table('orderpayment')
    op.drop_index(op.f('ix_orderitem_seller_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_product_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_order_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_table('todo')
    op.drop_index(op.f('ix_seller_seller_zip_code_prefix'), table_name='seller')
    op.drop_table('seller')
    op.drop_table('productcategorynametranslation')
    op.drop_index(op.f('ix_product_product_category_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_geolocation_geolocation_zip_code_prefix'), table_name='geolocation')
    op.drop_table('geolocation')
    op.drop_index(op.f('ix_customer_customer_zip_code_prefix'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_unique_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
