"""memory tables

Revision ID: 760d2a2163bb
Revises: 35a8cfc36763
Create Date: 2026-09-03 22:09:34.436663

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "760d2a2163bb"
down_revision: str | Sequence[str] | None = "35a8cfc36763"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_memories",
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    op.create_index(
        op.f("ix_user_memories_category"), "user_memories", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_user_memories_user_id"), "user_memories", ["user_id"], unique=False
    )
    op.create_table(
        "conversation_summary_memories",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("last_summarized_message_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.conversation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_foreign_key(
        "fk_conversations_last_message_id_messages",
        "conversations",
        "messages",
        ["last_message_id"],
        ["message_id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_conversations_last_message_id_messages", "conversations", type_="foreignkey"
    )
    op.drop_table("conversation_summary_memories")
    op.drop_index(op.f("ix_user_memories_user_id"), table_name="user_memories")
    op.drop_index(op.f("ix_user_memories_category"), table_name="user_memories")
    op.drop_table("user_memories")
    # ### end Alembic commands ###
